name: jobrouter
type: php
docroot: public
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
mariadb_version: "10.5"
omit_containers: [dba, ddev-ssh-agent]
use_dns_when_possible: true
timezone: UTC
